//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbfshr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentItem
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public int CategoryId { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
        public int StatusId { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
    }
}
